// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";
import { resolveSupabaseEnvironment } from "./lib/config/supabaseEnvironmentRuntime";

config({ path: ".env.local" });
config({ path: ".env" });

const generateOnly = process.env.PRISMA_GENERATE_ONLY === "true";
const datasourceUrl = generateOnly
  ? "postgresql://generate:generate@localhost:5432/generate"
  : resolveSupabaseEnvironment({ mode: "migration", env: process.env }).directUrl!;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: datasourceUrl,
  },
});
