// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run as the owner role via a direct (non-pooled) connection.
    // Runtime DATABASE_URL connects as a non-owner role so RLS applies.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"]!,
  },
});
